<?php

namespace OffbeatWP\LocalSeo;

class AddSeoFields
{
    const ID = 'local-seo';
    const PRIORITY = 1;

    public function title()
    {
        return __('Seo', 'raow');
    }

    public function form()
    {

        $form = new \OffbeatWP\Form\Form();
        $form->addTab('general-information', 'General information');
        $form->addField(\OffbeatWP\Form\Fields\Text::make('company_name', 'Company name'));

        $priceRange = \OffbeatWP\Form\Fields\Select::make('company_price_range', 'Price class');
        $localCompanyKind = \OffbeatWP\Form\Fields\Select::make('company_kind', 'Company Kind');


        $priceRange->addOptions(['$$$' => '$$$', '$$' => '$$', '$' => '$']);

        $form->addField($priceRange);

        $openingsdays = \OffbeatWP\Form\Fields\Select::make('opening_hours', 'Openings Hours');

        $openingsdays->addOptions([
            'Monday' => 'Monday',
            'Tuesday' => 'Tuesday',
            'Wednesday' => 'Wednesday',
            'Thursday' => 'Thursday',
            'Friday' => 'Friday',
            'Saturday' => 'Saturday',
            'Sunday' => 'Sunday',
        ]);

        $localCompanyKind->addOptions([
            'AnimalShelter' => 'AnimalShelter',
            'ArchiveOrganization' => 'ArchiveOrganization',
            'AutomotiveBusiness' => 'AutomotiveBusiness',
            'AutoBodyShop' => 'AutoBodyShop',
            'AutoDealer' => 'AutoDealer',
            'AutoPartsStore' => 'AutoPartsStore',
            'AutoRental' => 'AutoRental',
            'AutoRepair' => 'AutoRepair',
            'AutoWash' => 'AutoWash',
            'GasStation' => 'GasStation',
            'MotorcycleDealer' => 'MotorcycleDealer',
            'MotorcycleRepair' => 'MotorcycleRepair',
            'ChildCare' => 'ChildCare',
            'Dentist' => 'Dentist',
            'DryCleaningOrLaundry' => 'DryCleaningOrLaundry',
            'EmergencyService' => 'EmergencyService',
            'FireStation' => 'FireStation',
            'Hospital' => 'Hospital',
            'PoliceStation' => 'PoliceStation',
            'EmploymentAgency' => 'EmploymentAgency',
            'EntertainmentBusiness' => 'EntertainmentBusiness',
            'AdultEntertainment' => 'AdultEntertainment',
            'AmusementPark' => 'AmusementPark',
            'ArtGallery' => 'ArtGallery',
            'Casino' => 'Casino',
            'ComedyClub' => 'ComedyClub',
            'MovieTheater' => 'MovieTheater',
            'NightClub' => 'NightClub',
            'FinancialService' => 'FinancialService',
            'AccountingService' => 'AccountingService',
            'AutomatedTeller' => 'AutomatedTeller',
            'BankOrCreditUnion' => 'BankOrCreditUnion',
            'InsuranceAgency' => 'InsuranceAgency',
            'FoodEstablishment' => 'FoodEstablishment',
            'Bakery' => 'Bakery',
            'BarOrPub' => 'BarOrPub',
            'Brewery' => 'Brewery',
            'CafeOrCoffeeShop' => 'CafeOrCoffeeShop',
            'Distillery' => 'Distillery',
            'FastFoodRestaurant' => 'FastFoodRestaurant',
            'IceCreamShop' => 'IceCreamShop',
            'Restaurant' => 'Restaurant',
            'Winery' => 'Winery',
            'GovernmentOffice' => 'GovernmentOffice',
            'PostOffice' => 'PostOffice',
            'HealthAndBeautyBusiness' => 'HealthAndBeautyBusiness',
            'BeautySalon' => 'BeautySalon',
            'DaySpa' => 'DaySpa',
            'HairSalon' => 'HairSalon',
            'HealthClub' => 'HealthClub',
            'NailSalon' => 'NailSalon',
            'TattooParlor' => 'TattooParlor',
            'HomeAndConstructionBusiness' => 'HomeAndConstructionBusiness',
            'Electrician' => 'Electrician',
            'GeneralContractor' => 'GeneralContractor',
            'HVACBusiness' => 'HVACBusiness',
            'HousePainter' => 'HousePainter',
            'Locksmith' => 'Locksmith',
            'MovingCompany' => 'MovingCompany',
            'Plumber' => 'Plumber',
            'RoofingContractor' => 'RoofingContractor',
            'InternetCafe' => 'InternetCafe',
            'LegalService' => 'LegalService',
            'Attorney' => 'Attorney',
            'Notary' => 'Notary',
            'Library' => 'Library',
            'LodgingBusiness' => 'LodgingBusiness',
            'BedAndBreakfast' => 'BedAndBreakfast',
            'Campground' => 'Campground',
            'Hostel' => 'Hostel',
            'Hotel' => 'Hotel',
            'Motel' => 'Motel',
            'Resort' => 'Resort',
            'MedicalBusiness' => 'MedicalBusiness',
            'CommunityHealth ' => 'CommunityHealth',
            'Dentist ' => 'Dentist',
            'Dermatology ' => 'Dermatology',
            'DietNutrition ' => 'DietNutrition',
            'Emergency ' => 'Emergency',
            'Geriatric ' => 'Geriatric',
            'Gynecologic ' => 'Gynecologic',
            'MedicalClinic' => 'MedicalClinic',
            'Midwifery ' => 'Midwifery',
            'Nursing ' => 'Nursing',
            'Obstetric ' => 'Obstetric',
            'Oncologic ' => 'Oncologic',
            'Optician' => 'Optician',
            'Optometric ' => 'Optometric',
            'Otolaryngologic ' => 'Otolaryngologic',
            'Pediatric ' => 'Pediatric',
            'Pharmacy' => 'Pharmacy',
            'Physician' => 'Physician',
            'Physiotherapy ' => 'Physiotherapy',
            'PlasticSurgery ' => 'PlasticSurgery',
            'Podiatric ' => 'Podiatric',
            'PrimaryCare ' => 'PrimaryCare',
            'Psychiatric ' => 'Psychiatric',
            'PublicHealth ' => 'PublicHealth',
            'ProfessionalService' => 'ProfessionalService',
            'RadioStation' => 'RadioStation',
            'RealEstateAgent' => 'RealEstateAgent',
            'RecyclingCenter' => 'RecyclingCenter',
            'SelfStorage' => 'SelfStorage',
            'ShoppingCenter' => 'ShoppingCenter',
            'SportsActivityLocation' => 'SportsActivityLocation',
            'BowlingAlley' => 'BowlingAlley',
            'ExerciseGym' => 'ExerciseGym',
            'GolfCourse' => 'GolfCourse',
            'HealthClub ' => 'HealthClub',
            'PublicSwimmingPool' => 'PublicSwimmingPool',
            'SkiResort' => 'SkiResort',
            'SportsClub' => 'SportsClub',
            'StadiumOrArena' => 'StadiumOrArena',
            'TennisComplex' => 'TennisComplex',
            'Store' => 'Store',
            'AutoPartsStore ' => 'AutoPartsStore',
            'BikeStore' => 'BikeStore',
            'BookStore' => 'BookStore',
            'ClothingStore' => 'ClothingStore',
            'ComputerStore' => 'ComputerStore',
            'ConvenienceStore' => 'ConvenienceStore',
            'DepartmentStore' => 'DepartmentStore',
            'ElectronicsStore' => 'ElectronicsStore',
            'Florist' => 'Florist',
            'FurnitureStore' => 'FurnitureStore',
            'GardenStore' => 'GardenStore',
            'GroceryStore' => 'GroceryStore',
            'HardwareStore' => 'HardwareStore',
            'HobbyShop' => 'HobbyShop',
            'HomeGoodsStore' => 'HomeGoodsStore',
            'JewelryStore' => 'JewelryStore',
            'LiquorStore' => 'LiquorStore',
            'MensClothingStore' => 'MensClothingStore',
            'MobilePhoneStore' => 'MobilePhoneStore',
            'MovieRentalStore' => 'MovieRentalStore',
            'MusicStore' => 'MusicStore',
            'OfficeEquipmentStore' => 'OfficeEquipmentStore',
            'OutletStore' => 'OutletStore',
            'PawnShop' => 'PawnShop',
            'PetStore' => 'PetStore',
            'ShoeStore' => 'ShoeStore',
            'SportingGoodsStore' => 'SportingGoodsStore',
            'TireShop' => 'TireShop',
            'ToyStore' => 'ToyStore',
            'WholesaleStore' => 'WholesaleStore',
            'TelevisionStation' => 'TelevisionStation',
            'TouristInformationCenter' => 'TouristInformationCenter',
            'TravelAgency' => 'TravelAgency',
            'MedicalOrganization' => 'MedicalOrganization',
            'Dentist ' => 'Dentist',
            'DiagnosticLab' => 'DiagnosticLab',
            'Hospital ' => 'Hospital',
            'MedicalClinic ' => 'MedicalClinic',
            'Pharmacy ' => 'Pharmacy',
            'Physician ' => 'Physician',
            'VeterinaryCare' => 'VeterinaryCare',
        ]);


        $time = [
            '7:00' => '7:00',
            '8:00' => '8:00',
            '9:00' => '9:00',
            '10:00' => '10:00',
            '11:00' => '11:00',
            '12:00' => '12:00',
            '13:00' => '13:00',
            '14:00' => '14:00',
            '15:00' => '15:00',
            '16:00' => '16:00',
            '17:00' => '17:00',
            '18:00' => '18:00',
            '19:00' => '19:00',
            '20:00' => '20:00',
            '21:00' => '21:00',
            '22:00' => '22:00',
            '23:00' => '23:00',
            '24:00' => '24:00',
            '1:00' => '1:00',
            '2:00' => '2:00',
            '3:00' => '3:00',
            '4:00' => '4:00',
            '5:00' => '5:00',
            '6:00' => '6:00',
        ];

        $countries =  \OffbeatWP\Form\Fields\Select::make('countries', 'Countries');

        $countries->addOptions(

            [
                "AF" => "Afghanistan",
                "AL" => "Albania",
                "DZ" => "Algeria",
                "AS" => "American Samoa",
                "AD" => "Andorra",
                "AO" => "Angola",
                "AI" => "Anguilla",
                "AQ" => "Antarctica",
                "AG" => "Antigua and Barbuda",
                "AR" => "Argentina",
                "AM" => "Armenia",
                "AW" => "Aruba",
                "AU" => "Australia",
                "AT" => "Austria",
                "AZ" => "Azerbaijan",
                "BS" => "Bahamas",
                "BH" => "Bahrain",
                "BD" => "Bangladesh",
                "BB" => "Barbados",
                "BY" => "Belarus",
                "BE" => "Belgium",
                "BZ" => "Belize",
                "BJ" => "Benin",
                "BM" => "Bermuda",
                "BT" => "Bhutan",
                "BO" => "Bolivia",
                "BA" => "Bosnia and Herzegovina",
                "BW" => "Botswana",
                "BV" => "Bouvet Island",
                "BR" => "Brazil",
                "IO" => "British Indian Ocean Territory",
                "BN" => "Brunei Darussalam",
                "BG" => "Bulgaria",
                "BF" => "Burkina Faso",
                "BI" => "Burundi",
                "KH" => "Cambodia",
                "CM" => "Cameroon",
                "CA" => "Canada",
                "CV" => "Cape Verde",
                "KY" => "Cayman Islands",
                "CF" => "Central African Republic",
                "TD" => "Chad",
                "CL" => "Chile",
                "CN" => "China",
                "CX" => "Christmas Island",
                "CC" => "Cocos (Keeling) Islands",
                "CO" => "Colombia",
                "KM" => "Comoros",
                "CG" => "Congo",
                "CD" => "Congo, the Democratic Republic of the",
                "CK" => "Cook Islands",
                "CR" => "Costa Rica",
                "CI" => "Cote D'Ivoire",
                "HR" => "Croatia",
                "CU" => "Cuba",
                "CY" => "Cyprus",
                "CZ" => "Czech Republic",
                "DK" => "Denmark",
                "DJ" => "Djibouti",
                "DM" => "Dominica",
                "DO" => "Dominican Republic",
                "EC" => "Ecuador",
                "EG" => "Egypt",
                "SV" => "El Salvador",
                "GQ" => "Equatorial Guinea",
                "ER" => "Eritrea",
                "EE" => "Estonia",
                "ET" => "Ethiopia",
                "FK" => "Falkland Islands (Malvinas)",
                "FO" => "Faroe Islands",
                "FJ" => "Fiji",
                "FI" => "Finland",
                "FR" => "France",
                "GF" => "French Guiana",
                "PF" => "French Polynesia",
                "TF" => "French Southern Territories",
                "GA" => "Gabon",
                "GM" => "Gambia",
                "GE" => "Georgia",
                "DE" => "Germany",
                "GH" => "Ghana",
                "GI" => "Gibraltar",
                "GR" => "Greece",
                "GL" => "Greenland",
                "GD" => "Grenada",
                "GP" => "Guadeloupe",
                "GU" => "Guam",
                "GT" => "Guatemala",
                "GN" => "Guinea",
                "GW" => "Guinea-Bissau",
                "GY" => "Guyana",
                "HT" => "Haiti",
                "HM" => "Heard Island and Mcdonald Islands",
                "VA" => "Holy See (Vatican City State)",
                "HN" => "Honduras",
                "HK" => "Hong Kong",
                "HU" => "Hungary",
                "IS" => "Iceland",
                "IN" => "India",
                "ID" => "Indonesia",
                "IR" => "Iran, Islamic Republic of",
                "IQ" => "Iraq",
                "IE" => "Ireland",
                "IL" => "Israel",
                "IT" => "Italy",
                "JM" => "Jamaica",
                "JP" => "Japan",
                "JO" => "Jordan",
                "KZ" => "Kazakhstan",
                "KE" => "Kenya",
                "KI" => "Kiribati",
                "KP" => "Korea, Democratic People's Republic of",
                "KR" => "Korea, Republic of",
                "KW" => "Kuwait",
                "KG" => "Kyrgyzstan",
                "LA" => "Lao People's Democratic Republic",
                "LV" => "Latvia",
                "LB" => "Lebanon",
                "LS" => "Lesotho",
                "LR" => "Liberia",
                "LY" => "Libyan Arab Jamahiriya",
                "LI" => "Liechtenstein",
                "LT" => "Lithuania",
                "LU" => "Luxembourg",
                "MO" => "Macao",
                "MK" => "Macedonia, the Former Yugoslav Republic of",
                "MG" => "Madagascar",
                "MW" => "Malawi",
                "MY" => "Malaysia",
                "MV" => "Maldives",
                "ML" => "Mali",
                "MT" => "Malta",
                "MH" => "Marshall Islands",
                "MQ" => "Martinique",
                "MR" => "Mauritania",
                "MU" => "Mauritius",
                "YT" => "Mayotte",
                "MX" => "Mexico",
                "FM" => "Micronesia, Federated States of",
                "MD" => "Moldova, Republic of",
                "MC" => "Monaco",
                "MN" => "Mongolia",
                "MS" => "Montserrat",
                "MA" => "Morocco",
                "MZ" => "Mozambique",
                "MM" => "Myanmar",
                "NA" => "Namibia",
                "NR" => "Nauru",
                "NP" => "Nepal",
                "NL" => "Netherlands",
                "AN" => "Netherlands Antilles",
                "NC" => "New Caledonia",
                "NZ" => "New Zealand",
                "NI" => "Nicaragua",
                "NE" => "Niger",
                "NG" => "Nigeria",
                "NU" => "Niue",
                "NF" => "Norfolk Island",
                "MP" => "Northern Mariana Islands",
                "NO" => "Norway",
                "OM" => "Oman",
                "PK" => "Pakistan",
                "PW" => "Palau",
                "PS" => "Palestinian Territory, Occupied",
                "PA" => "Panama",
                "PG" => "Papua New Guinea",
                "PY" => "Paraguay",
                "PE" => "Peru",
                "PH" => "Philippines",
                "PN" => "Pitcairn",
                "PL" => "Poland",
                "PT" => "Portugal",
                "PR" => "Puerto Rico",
                "QA" => "Qatar",
                "RE" => "Reunion",
                "RO" => "Romania",
                "RU" => "Russian Federation",
                "RW" => "Rwanda",
                "SH" => "Saint Helena",
                "KN" => "Saint Kitts and Nevis",
                "LC" => "Saint Lucia",
                "PM" => "Saint Pierre and Miquelon",
                "VC" => "Saint Vincent and the Grenadines",
                "WS" => "Samoa",
                "SM" => "San Marino",
                "ST" => "Sao Tome and Principe",
                "SA" => "Saudi Arabia",
                "SN" => "Senegal",
                "CS" => "Serbia and Montenegro",
                "SC" => "Seychelles",
                "SL" => "Sierra Leone",
                "SG" => "Singapore",
                "SK" => "Slovakia",
                "SI" => "Slovenia",
                "SB" => "Solomon Islands",
                "SO" => "Somalia",
                "ZA" => "South Africa",
                "GS" => "South Georgia and the South Sandwich Islands",
                "ES" => "Spain",
                "LK" => "Sri Lanka",
                "SD" => "Sudan",
                "SR" => "Suriname",
                "SJ" => "Svalbard and Jan Mayen",
                "SZ" => "Swaziland",
                "SE" => "Sweden",
                "CH" => "Switzerland",
                "SY" => "Syrian Arab Republic",
                "TW" => "Taiwan, Province of China",
                "TJ" => "Tajikistan",
                "TZ" => "Tanzania, United Republic of",
                "TH" => "Thailand",
                "TL" => "Timor-Leste",
                "TG" => "Togo",
                "TK" => "Tokelau",
                "TO" => "Tonga",
                "TT" => "Trinidad and Tobago",
                "TN" => "Tunisia",
                "TR" => "Turkey",
                "TM" => "Turkmenistan",
                "TC" => "Turks and Caicos Islands",
                "TV" => "Tuvalu",
                "UG" => "Uganda",
                "UA" => "Ukraine",
                "AE" => "United Arab Emirates",
                "GB" => "United Kingdom",
                "US" => "United States",
                "UM" => "United States Minor Outlying Islands",
                "UY" => "Uruguay",
                "UZ" => "Uzbekistan",
                "VU" => "Vanuatu",
                "VE" => "Venezuela",
                "VN" => "Viet Nam",
                "VG" => "Virgin Islands, British",
                "VI" => "Virgin Islands, U.s.",
                "WF" => "Wallis and Futuna",
                "EH" => "Western Sahara",
                "YE" => "Yemen",
                "ZM" => "Zambia",
                "ZW" => "Zimbabwe",
            ]);

        $closingTime = \OffbeatWP\Form\Fields\Select::make('closing_time', 'Closing time');
        $openingHours = \OffbeatWP\Form\Fields\Select::make('opening_time', 'Opening time');
        $closingTime->addOptions($time);
        $openingHours->addOptions($time);
        $form->addField($localCompanyKind);
        $form->addTab('contact-information', 'Contact details');
        $form->addField(\OffbeatWP\Form\Fields\Text::make('company_fax', 'Fax number'));
        $form->addField(\OffbeatWP\Form\Fields\Text::make('company_phone', 'Telephone number'));
        $form->addField(\OffbeatWP\Form\Fields\Text::make('company_street', 'Street'));
        $form->addField(\OffbeatWP\Form\Fields\Text::make('company_number', 'Number'));
        $form->addField(\OffbeatWP\Form\Fields\Text::make('company_zip_code', 'Zip code'));
        $form->addField(\OffbeatWP\Form\Fields\Text::make('company_place', 'Place (City)'));
        $form->addField(\OffbeatWP\Form\Fields\Text::make('company_province', 'Province'));
        $form->addField($countries);
        $form->addTab('opening-hours', 'Opening hours');
        $form->addRepeater('opening-hours-selector',
            'Opening hours')->addField($openingsdays)->addField($openingHours)->addField($closingTime);

        return $form;

    }
}
